name: "Example Action"
on:
  push:
    branches:
      - main
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "CF Deploy"
        uses: maxhagn/CloudFoundryDeployAction@v1.0.0
        with:
          CF_API: "${{ secrets.CF_API }}"
          CF_USERNAME: "${{ secrets.CF_USERNAME }}"
          CF_PASSWORD: "${{ secrets.CF_PASSWORD }}"
          CF_ORG: "my-org"
          CF_SPACE: "my-space"
          CF_COMMAND: "deploy gen/mta.tar"