name: "Test CF Deployment Action"

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Run CF Deployment Action"
        uses: ./
        with:
          CF_API: "https://api.cf.eu10-004.hana.ondemand.com"
          CF_USERNAME: "maximilian.hagn@scc.at"
          CF_PASSWORD: "Nepomuk1997Nepomuk301"
          CF_ORG: "scc-toolbox"
          CF_SPACE: "dev"
          CF_COMMAND: "deploy gen/mta.tar"